version: "3.7"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db:/db

  server:
    build:
      context: server
      dockerfile: Dockerfile
    env_file:
      - server/.env-prod
    container_name: server
    ports:
      - 8000:8000
    depends_on:
      - mongodb
#  bot:
#    build:
#      context: client
#      dockerfile: Dockerfile
#    env_file:
#      - client/.env-prod
#    container_name: bot
volumes:
  db:

